##
# Run Mapserver in a development environment.
#

version: '3'
services:
  mapserver:
    build: .
    hostname: mapserver
    volumes:
      - ./:/maps
    working_dir: /maps

  webserver:
    image: nginx:1.13.3-alpine
    ports:
      - "8080:80"
    depends_on:
      - mapserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
