##
# Run Mapserver in a development environment.
#

version: '3'
services:
  mapserver:
    build: .
    hostname: mapserver
    volumes:
      - ./:/maps
    working_dir: /maps

  webserver:
    image: m4rcu5/lighttpd
    ports:
      - "8080:80"
    depends_on:
      - mapserver
    volumes:
      - ./:/etc/lighttpd
    command: ["lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd.conf"]
